### ISSUE TITLE
Could it work on dicovery F3?

### ISSUE THREAD

**Issue by VioletGiraffe** [10110111/usb2ps2conv#1]
Hello, and first of all - thanks for this great and very useful project!
I have a Discovery F3 board, can the project be [easily] retargeted to it?

**Comment by 10110111** [comment]
Sorry, but from [the manual](https://www.st.com/resource/en/user_manual/dm00063382-discovery-kit-with-stm32f303vc-mcu-stmicroelectronics.pdf) it seems the chip that's used there, STM32F303VC, doesn't support USB Host mode. Only USB Device mode is supported, i.e. the chip could e.g. act as a keyboard, but not talk to another keyboard.

**Comment by VioletGiraffe** [comment]
Thank you! And sorry for not checking that myself, for some reason I was 100% sure F3 also supports USB host mode.
