### ISSUE TITLE
Pinout Question

### ISSUE THREAD

**Issue by alberk8** [10110111/usb2ps2conv#2]
Hi,

Do you have a image/picture of the pinout connections from the development board to USB as well as the PS/2 ?   Thank you.

**Comment by 10110111** [comment]
Here is how I did it:

![IMG_20210210_122245](https://user-images.githubusercontent.com/6376882/107490457-f9804200-6b9a-11eb-9a2a-49ba2b133742.jpg)

**Comment by 10110111** [comment]
I'm assuming you're satisfied with my reply, so closing this issue. If my assumption is wrong, feel free to re-open and say what exactly I've missed.
